services:
  proxy:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./proxy/default.conf.template:/etc/nginx/templates/default.conf.template
    ports:
      - "80:80"

  api:
    build: ./api
    restart: unless-stopped
    volumes:
      - ./api/src:/app/src
      - ./api/static:/app/static
    environment:
      - PORT=80
    env_file:
      - ./api/.env

  frontend:
    build: ./frontend
    restart: unless-stopped
    volumes:
      - ./frontend/src:/app/src
    environment:
      - PORT=80
